/**
 * 学习计划数据模型
 */
const { pool } = require('../config/database');

class LearningPlanModel {
  static async create(userId, { 
    name, 
    goal, 
    targetDate, 
    goalType = 'skill',
    targetScore = null,
    startDate = null,
    endDate = null,
    dailyStudyMinutes = 60,
    courseId = null,
    examId = null,
    priority = 'medium',
    autoGenerated = false
  }) {
    const sql = `
      INSERT INTO learning_plan (
        user_id, name, goal, target_date, 
        goal_type, target_score, start_date, end_date,
        daily_study_minutes, course_id, exam_id, priority, auto_generated,
        status, progress, created_at, updated_at
      )
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'draft', 0, NOW(), NOW())
    `;
    const [result] = await pool.execute(sql, [
      userId, name, goal, targetDate || null,
      goalType, targetScore, startDate, endDate,
      dailyStudyMinutes, courseId, examId, priority, autoGenerated
    ]);
    return result.insertId;
  }

  static async findByUserId(userId) {
    const sql = `
      SELECT * FROM learning_plan
      WHERE user_id = ?
      ORDER BY 
        CASE priority 
          WHEN 'high' THEN 1 
          WHEN 'medium' THEN 2 
          WHEN 'low' THEN 3 
        END,
        created_at DESC
    `;
    const [rows] = await pool.execute(sql, [userId]);
    return rows;
  }

  static async findById(id, userId) {
    const sql = 'SELECT * FROM learning_plan WHERE id = ? AND user_id = ?';
    const [rows] = await pool.execute(sql, [id, userId]);
    return rows[0];
  }

  static async update(id, userId, { 
    name, goal, targetDate, 
    goalType, targetScore, startDate, endDate,
    dailyStudyMinutes, courseId, examId, priority,
    reviewNotes, totalTasks, totalMinutes
  }) {
    const sql = `
      UPDATE learning_plan
      SET name = COALESCE(?, name),
          goal = COALESCE(?, goal),
          target_date = COALESCE(?, target_date),
          goal_type = COALESCE(?, goal_type),
          target_score = COALESCE(?, target_score),
          start_date = COALESCE(?, start_date),
          end_date = COALESCE(?, end_date),
          daily_study_minutes = COALESCE(?, daily_study_minutes),
          course_id = COALESCE(?, course_id),
          exam_id = COALESCE(?, exam_id),
          priority = COALESCE(?, priority),
          review_notes = COALESCE(?, review_notes),
          total_tasks = COALESCE(?, total_tasks),
          total_minutes = COALESCE(?, total_minutes),
          updated_at = NOW()
      WHERE id = ? AND user_id = ?
    `;
    await pool.execute(sql, [
      name ?? null, goal ?? null, targetDate ?? null,
      goalType ?? null, targetScore ?? null, startDate ?? null, endDate ?? null,
      dailyStudyMinutes ?? null, courseId ?? null, examId ?? null, priority ?? null,
      reviewNotes ?? null, totalTasks ?? null, totalMinutes ?? null, id, userId
    ]);
  }

  static async delete(id, userId) {
    const sql = 'DELETE FROM learning_plan WHERE id = ? AND user_id = ?';
    const [result] = await pool.execute(sql, [id, userId]);
    return result.affectedRows > 0;
  }

  static async updateProgress(id, userId, progress) {
    const sql = `
      UPDATE learning_plan
      SET progress = ?, updated_at = NOW()
      WHERE id = ? AND user_id = ?
    `;
    await pool.execute(sql, [progress, id, userId]);
  }

  static async updateStatus(id, userId, status) {
    let sql = 'UPDATE learning_plan SET status = ?, updated_at = NOW()';
    const params = [status];
    
    if (status === 'completed') {
      sql += ', completed_at = NOW()';
    }
    
    sql += ' WHERE id = ? AND user_id = ?';
    params.push(id, userId);
    
    await pool.execute(sql, params);
  }

  static async findActiveByUserId(userId) {
    const sql = `
      SELECT id, name
      FROM learning_plan
      WHERE user_id = ? AND status = 'active'
      ORDER BY created_at DESC
    `;
    const [rows] = await pool.execute(sql, [userId]);
    return rows;
  }

  static async updateProgressByTasks(planId, userId) {
    const sql = `
      SELECT 
        COUNT(*) as total,
        SUM(CASE WHEN status = 2 THEN 1 ELSE 0 END) as completed
      FROM learning_tasks
      WHERE plan_id = ? AND user_id = ?
    `;
    const [rows] = await pool.execute(sql, [planId, userId]);
    const { total, completed } = rows[0];
    
    const progress = total > 0 ? Math.round((completed / total) * 100) : 0;
    
    await this.updateProgress(planId, userId, progress);
    
    const updateSql = `
      UPDATE learning_plan
      SET total_tasks = ?, completed_tasks = ?
      WHERE id = ? AND user_id = ?
    `;
    await pool.execute(updateSql, [total, completed, planId, userId]);
    
    if (progress >= 100) {
      await this.updateStatus(planId, userId, 'completed');
    }
    
    return progress;
  }

  static async updateTotalMinutes(planId, minutes) {
    const sql = `
      UPDATE learning_plan
      SET total_minutes = total_minutes + ?
      WHERE id = ?
    `;
    await pool.execute(sql, [minutes, planId]);
  }

  static async findByStatus(userId, status) {
    const sql = `
      SELECT * FROM learning_plan
      WHERE user_id = ? AND status = ?
      ORDER BY created_at DESC
    `;
    const [rows] = await pool.execute(sql, [userId, status]);
    return rows;
  }

  static async countByUser(userId) {
    const sql = 'SELECT COUNT(*) as count FROM learning_plan WHERE user_id = ?';
    const [rows] = await pool.execute(sql, [userId]);
    return rows[0].count;
  }

  static async countByUserAndStatus(userId, status) {
    const sql = 'SELECT COUNT(*) as count FROM learning_plan WHERE user_id = ? AND status = ?';
    const [rows] = await pool.execute(sql, [userId, status]);
    return rows[0].count;
  }
}

module.exports = LearningPlanModel;