/**
 * 学习计划控制器
 */
const { pool } = require('../config/database');
const LearningPlanService = require('../services/LearningPlanService');
const LearningPlanModel = require('../models/LearningPlanModel');
const PlanPhaseModel = require('../models/PlanPhaseModel');
const LearningTaskModel = require('../models/LearningTaskModel');
const PlanningAgent = require('../services/PlanningAgent');
const { ProfileModel, MasteredTopicModel } = require('../models/ProfileModel');
const { cache } = require('../services/CacheService');
const { success, fail } = require('../utils/response');
const logger = require('../config/logger');
const { identifyFoundationTasks, assignSequenceOrder } = require('../utils/taskPriority');

class PlanController {
  static async createPlan(req, res) {
    try {
      const userId = req.user.userId;
      const { name, goal, targetDate, knowledgePoints, dailyStudyMinutes } = req.body;

      if (!name) {
        return res.status(400).json(fail('计划名称不能为空'));
      }

      const limitCheck = await LearningPlanService.checkCreateLimit(userId);
      if (!limitCheck.canCreate) {
        return res.status(400).json(fail(limitCheck.reason));
      }

      const result = await LearningPlanService.createPlan(userId, {
        name,
        goal,
        targetDate,
        knowledgePoints: knowledgePoints || [],
        dailyStudyMinutes: dailyStudyMinutes || 60
      });

      logger.info(`创建学习计划: ${name}, 任务数: ${result.taskCount}, 每日时长: ${dailyStudyMinutes || 60}分钟`);

      res.json(success(result, '创建成功'));
    } catch (error) {
      logger.error('创建学习计划失败:', error.message);
      res.status(500).json(fail(error.message));
    }
  }

  static async createDraft(req, res) {
    try {
      const userId = req.user.userId;
      const {
        name,
        description,
        goalType,
        courseId,
        examId,
        targetScore,
        endDate,
        dailyStudyMinutes,
        priority
      } = req.body;

      if (!name) {
        return res.status(400).json(fail('计划名称不能为空'));
      }

      if (!endDate) {
        return res.status(400).json(fail('预计完成日期不能为空'));
      }

      const limitCheck = await LearningPlanService.checkCreateLimit(userId);
      if (!limitCheck.canCreate) {
        return res.status(400).json(fail(limitCheck.reason));
      }

      const planId = await LearningPlanModel.create(userId, {
        name,
        goal: description,
        goalType,
        courseId,
        examId,
        targetScore,
        endDate,
        dailyStudyMinutes: dailyStudyMinutes || 60,
        priority: priority || 'medium',
        autoGenerated: true
      });

      logger.info(`创建计划草稿: 用户${userId}, 计划${planId}, 名称${name}`);

      res.status(201).json(success({ id: planId }, '草稿创建成功'));
    } catch (error) {
      logger.error('创建计划草稿失败:', error.message);
      res.status(500).json(fail('创建失败'));
    }
  }

  static async generatePlan(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const userProfile = await ProfileModel.getProfile(userId);
      const masteredTopics = await MasteredTopicModel.getUserMasteredTopicIds(userId);

      const subject = PlanController.extractSubject(plan.goal || plan.name);

      const agentParams = {
        userId,
        target: plan.goal || plan.name,
        goalType: plan.goal_type || 'skill',
        subject: subject,
        userLevel: userProfile?.overall_level || 'beginner',
        masteredTopicIds: masteredTopics || [],
        learningPace: userProfile?.learning_pace || 'normal',
        dailyStudyMinutes: plan.daily_study_minutes || userProfile?.daily_available_minutes || 60,
        availableWeekdays: userProfile?.available_weekdays || [1, 2, 3, 4, 5, 6, 7],
        deadline: plan.end_date || plan.target_date,
        targetScore: plan.target_score,
        focusTopicIds: [],
        preferExercise: userProfile?.prefer_exercise !== false
      };

      const result = await PlanningAgent.generatePlan(agentParams);

      logger.info(`生成学习路径: 计划${planId}, 阶段数${result.plan.phases.length}, 任务数${result.plan.stats.totalTasks}`);

      res.json(success(result, '生成成功'));
    } catch (error) {
      logger.error('生成学习路径失败:', error.message);
      res.status(500).json(fail('生成失败'));
    }
  }

  static extractSubject(text) {
    const subjectKeywords = {
      'Java': ['java', 'jdk', 'jvm', 'spring', 'javaweb', 'javaee', 'javase'],
      'Python': ['python', 'django', 'flask', '爬虫', '数据分析', '机器学习', '深度学习', '人工智能', 'ai'],
      'JavaScript': ['javascript', 'js', 'vue', 'react', 'node', '前端', 'web开发', 'typescript'],
      '高数': ['高数', '高等数学', '微积分', '极限', '导数', '积分', '微分方程', '数学分析'],
      '英语': ['英语', '四六级', 'cet', '考研英语', '雅思', '托福', 'gre', '英语口语'],
      '数学': ['数学', '线性代数', '概率论', '数理统计', '离散数学'],
      '物理': ['物理', '力学', '电磁学', '光学', '热学', '量子'],
      '化学': ['化学', '有机化学', '无机化学', '分析化学'],
      'C++': ['c++', 'cpp', 'c语言', 'c程序'],
      '计算机二级': ['计算机二级', '二级c', '二级office', '二级python', '二级java', 'ncre'],
      '数据库': ['数据库', 'sql', 'mysql', 'oracle', 'mongodb', 'redis']
    };
    
    const lowerText = (text || '').toLowerCase();
    
    for (const [subject, keywords] of Object.entries(subjectKeywords)) {
      for (const keyword of keywords) {
        if (lowerText.includes(keyword.toLowerCase())) {
          return subject;
        }
      }
    }

    return text || '通用';
  }

  static async confirmPlan(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);
      const { phases } = req.body;

      if (!phases || !Array.isArray(phases) || phases.length === 0) {
        return res.status(400).json(fail('缺少阶段数据'));
      }

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      let totalTasks = 0;
      let totalMinutes = 0;
      const createdPhases = [];

      for (let i = 0; i < phases.length; i++) {
        const phaseData = phases[i];
        
        if (!phaseData.tasks || !Array.isArray(phaseData.tasks)) {
          continue;
        }

        const phaseId = await PlanPhaseModel.create(planId, {
          name: phaseData.name,
          description: phaseData.description || null,
          phaseOrder: i + 1
        });

        const createdTasks = [];
        for (let j = 0; j < phaseData.tasks.length; j++) {
          const taskData = phaseData.tasks[j];
          
          if (!taskData.name) {
            continue;
          }

          const taskId = await LearningTaskModel.create(userId, {
            planId,
            phaseId,
            name: taskData.name,
            description: taskData.description || null,
            plannedDuration: taskData.estimatedMinutes || 60,
            plannedDate: taskData.scheduledDate || taskData.plannedDate || null,
            sortOrder: j + 1,
            difficulty: taskData.difficulty || 2
          });

          createdTasks.push(taskId);
          totalTasks++;
          totalMinutes += taskData.estimatedMinutes || 60;
        }

        await PlanPhaseModel.updateTaskCount(phaseId);
        createdPhases.push({ id: phaseId, taskCount: createdTasks.length });
      }

      await LearningPlanModel.update(planId, userId, {
        totalTasks,
        totalMinutes
      });

      await LearningPlanModel.updateStatus(planId, userId, 'active');

      const updatedPlan = await LearningPlanModel.findById(planId, userId);

      logger.info(`确认创建计划: 计划${planId}, 总任务${totalTasks}, 总时长${totalMinutes}分钟`);

      res.json(success(updatedPlan, '计划创建成功'));
    } catch (error) {
      logger.error('确认创建计划失败:', error.message);
      logger.error('错误堆栈:', error.stack);
      console.error('confirmPlan error:', error);
      res.status(500).json(fail(error.message || '创建失败'));
    }
  }

  static async getPlans(req, res) {
    try {
      const userId = req.user.userId;
      const plans = await LearningPlanService.getPlans(userId);

      res.json(success(plans));
    } catch (error) {
      logger.error('获取学习计划列表失败:', error.message);
      res.status(500).json(fail('获取失败'));
    }
  }

  static async getActivePlans(req, res) {
    try {
      const userId = req.user.userId;
      const plans = await LearningPlanModel.findActiveByUserId(userId);

      res.json(success(plans));
    } catch (error) {
      logger.error('获取进行中计划列表失败:', error.message);
      res.status(500).json(fail('获取失败'));
    }
  }

  static async getPlanDetail(req, res) {
    try {
      const userId = req.user.userId;
      const { id } = req.params;

      const result = await LearningPlanService.getPlanDetail(id, userId);

      res.json(success(result));
    } catch (error) {
      logger.error('获取计划详情失败:', error.message);
      res.status(500).json(fail(error.message));
    }
  }

  static async updatePlan(req, res) {
    try {
      const userId = req.user.userId;
      const { id } = req.params;
      const { 
        name, 
        goal, 
        targetDate, 
        target_date,
        dailyStudyMinutes, 
        daily_study_minutes,
        targetScore,
        target_score
      } = req.body;

      await LearningPlanService.updatePlan(id, userId, { 
        name, 
        goal, 
        targetDate: targetDate || target_date, 
        dailyStudyMinutes: dailyStudyMinutes || daily_study_minutes,
        targetScore: targetScore || target_score
      });

      res.json(success(null, '更新成功'));
    } catch (error) {
      logger.error('更新学习计划失败:', error.message);
      res.status(500).json(fail(error.message));
    }
  }

  static async deletePlan(req, res) {
    try {
      const userId = req.user.userId;
      const { id } = req.params;

      await LearningPlanService.deletePlan(id, userId);

      res.json(success(null, '删除成功'));
    } catch (error) {
      logger.error('删除学习计划失败:', error.message);
      res.status(500).json(fail(error.message));
    }
  }

  static async getFullDetail(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const phases = await PlanPhaseModel.findByPlanId(planId);
      
      const phasesWithTasks = await Promise.all(phases.map(async (phase) => {
        const tasks = await LearningTaskModel.findByPhaseId(phase.id);
        return {
          ...phase,
          tasks
        };
      }));

      const ddlTasks = await LearningTaskModel.findDDLByPlanId(planId, userId);

      let course = null;
      if (plan.course_id) {
        const [courseRows] = await pool.execute(
          'SELECT * FROM courses WHERE id = ?',
          [plan.course_id]
        );
        course = courseRows[0] || null;
      }

      let exam = null;
      if (plan.exam_id) {
        const [examRows] = await pool.execute(
          'SELECT * FROM exams WHERE id = ?',
          [plan.exam_id]
        );
        exam = examRows[0] || null;
      }

      const stats = {
        totalTasks: plan.total_tasks || 0,
        completedTasks: plan.completed_tasks || 0,
        totalMinutes: plan.total_minutes || 0,
        progress: plan.progress || 0,
        remainingTasks: (plan.total_tasks || 0) - (plan.completed_tasks || 0)
      };

      const EvaluationAgent = require('../services/EvaluationAgent');
      const riskAssessment = await EvaluationAgent.assessPlan(plan, phasesWithTasks, userId);

      res.json(success({
        plan,
        phases: phasesWithTasks,
        ddlTasks,
        course,
        exam,
        stats,
        riskAssessment
      }));
    } catch (error) {
      logger.error('获取计划完整详情失败:', error.message);
      res.status(500).json(fail('获取失败'));
    }
  }

  static async getProgressTrend(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const startDate = plan.start_date || plan.created_at;
      const endDate = plan.end_date || plan.target_date;

      const sql = `
        SELECT 
          DATE(completed_at) as date,
          COUNT(*) as completed_count
        FROM learning_tasks
        WHERE plan_id = ? AND user_id = ? AND status = 2 AND completed_at IS NOT NULL
        GROUP BY DATE(completed_at)
        ORDER BY date ASC
      `;
      const [actualProgress] = await pool.execute(sql, [planId, userId]);

      const plannedTasks = await LearningTaskModel.findByPlanId(planId, userId);
      const totalTasks = plannedTasks.length;
      
      const plannedProgress = [];
      if (startDate && endDate && totalTasks > 0) {
        const start = new Date(startDate);
        const end = new Date(endDate);
        const days = Math.ceil((end - start) / (1000 * 60 * 60 * 24));
        const tasksPerDay = totalTasks / Math.max(days, 1);
        
        let cumulative = 0;
        for (let i = 0; i <= days; i++) {
          const date = new Date(start);
          date.setDate(date.getDate() + i);
          cumulative += tasksPerDay;
          plannedProgress.push({
            date: date.toISOString().split('T')[0],
            count: Math.min(Math.round(cumulative), totalTasks)
          });
        }
      }

      let cumulativeActual = 0;
      const actualProgressCumulative = actualProgress.map(item => {
        cumulativeActual += item.completed_count;
        return {
          date: item.date,
          count: cumulativeActual
        };
      });

      res.json(success({
        planned: plannedProgress,
        actual: actualProgressCumulative,
        totalTasks
      }));
    } catch (error) {
      logger.error('获取进度趋势失败:', error.message);
      res.status(500).json(fail('获取失败'));
    }
  }

  static async reorderTasks(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);
      const { taskOrders } = req.body;

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      for (const item of taskOrders) {
        await LearningTaskModel.updateOrder(item.taskId, item.sortOrder, item.phaseId);
      }

      res.json(success(null, '排序更新成功'));
    } catch (error) {
      logger.error('更新任务排序失败:', error.message);
      res.status(500).json(fail('更新失败'));
    }
  }

  static async addTask(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);
      const { phaseId, name, description, estimatedMinutes, plannedDate } = req.body;

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const taskId = await LearningTaskModel.create(userId, {
        planId,
        phaseId,
        name,
        description,
        plannedDuration: estimatedMinutes || 60,
        plannedDate,
        sortOrder: 0,
        difficulty: 2
      });

      if (phaseId) {
        await PlanPhaseModel.updateTaskCount(phaseId);
      }

      await LearningPlanModel.updateProgressByTasks(planId, userId);

      logger.info(`添加任务: 计划${planId}, 任务${taskId}, 名称${name}`);

      res.status(201).json(success({ id: taskId }, '任务添加成功'));
    } catch (error) {
      logger.error('添加任务失败:', error.message);
      res.status(500).json(fail('添加失败'));
    }
  }

  static async replan(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);
      const { keepCompleted = true, triggerReason = '用户手动触发' } = req.body;

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const beforeTasks = await LearningTaskModel.findByPlanId(planId, userId);
      const beforeTaskCount = beforeTasks.length;
      const beforeEndDate = await LearningTaskModel.getMaxPlannedDate(planId, userId);

      const userProfile = await ProfileModel.getProfile(userId);
      const masteredTopics = await MasteredTopicModel.getUserMasteredTopicIds(userId);

      const subject = PlanController.extractSubject(plan.goal || plan.name);

      const agentParams = {
        userId,
        target: plan.goal || plan.name,
        goalType: plan.goal_type || 'skill',
        subject: subject,
        userLevel: userProfile?.overall_level || 'beginner',
        masteredTopicIds: masteredTopics || [],
        learningPace: userProfile?.learning_pace || 'normal',
        dailyStudyMinutes: plan.daily_study_minutes || userProfile?.daily_available_minutes || 60,
        availableWeekdays: userProfile?.available_weekdays || [1, 2, 3, 4, 5, 6, 7],
        deadline: plan.end_date || plan.target_date,
        targetScore: plan.target_score,
        focusTopicIds: [],
        preferExercise: userProfile?.prefer_exercise !== false
      };

      const result = await PlanningAgent.generatePlan(agentParams);

      let completedTasks = [];
      if (keepCompleted) {
        completedTasks = await LearningTaskModel.findCompletedByPlanId(planId, userId);
      }

      const foundationTasks = identifyFoundationTasks(beforeTasks);
      const foundationNames = new Set(foundationTasks.map(t => t.name));
      
      logger.info(`识别到 ${foundationTasks.length} 个前置基础任务需要保留顺序`);

      const deletedCount = await LearningTaskModel.deleteByPlanId(planId, userId, keepCompleted);
      await PlanPhaseModel.deleteByPlanId(planId);

      let totalTasks = completedTasks.length;
      let totalMinutes = 0;
      let globalSequence = 1;

      for (let i = 0; i < result.plan.phases.length; i++) {
        const phaseData = result.plan.phases[i];
        
        if (!phaseData.tasks || !Array.isArray(phaseData.tasks)) {
          continue;
        }

        const phaseId = await PlanPhaseModel.create(planId, {
          name: phaseData.name,
          description: phaseData.description || null,
          phaseOrder: i + 1
        });

        for (let j = 0; j < phaseData.tasks.length; j++) {
          const taskData = phaseData.tasks[j];
          
          if (!taskData.name) {
            continue;
          }

          if (foundationNames.has(taskData.name)) {
            logger.info(`跳过已存在的前置任务: ${taskData.name}`);
            continue;
          }

          logger.info(`创建任务: name=${taskData.name}, scheduledDate=${taskData.scheduledDate}, plannedDate=${taskData.plannedDate}, category=${taskData.category}`);

          await LearningTaskModel.create(userId, {
            planId,
            phaseId,
            name: taskData.name,
            description: taskData.description || taskData.reason || null,
            plannedDuration: taskData.estimatedMinutes || 60,
            plannedDate: taskData.scheduledDate || taskData.plannedDate || null,
            sortOrder: globalSequence,
            difficulty: taskData.difficulty || 2,
            category: taskData.category || 'cognitive',
            needsReview: taskData.needsReview !== false
          });

          globalSequence++;
          totalTasks++;
          totalMinutes += taskData.estimatedMinutes || 60;
        }

        await PlanPhaseModel.updateTaskCount(phaseId);
      }

      const afterEndDate = await LearningTaskModel.getMaxPlannedDate(planId, userId);

      const ReplanLogModel = require('../models/ReplanLogModel');
      await ReplanLogModel.create({
        planId,
        triggerReason,
        beforeTasks: beforeTaskCount,
        afterTasks: totalTasks,
        adjustedDates: {
          beforeEndDate,
          afterEndDate
        }
      });

      await LearningPlanModel.update(planId, userId, {
        totalTasks,
        totalMinutes
      });

      await LearningPlanModel.updateStatus(planId, userId, 'active');

      logger.info(`重新规划: 计划${planId}, 阶段数${result.plan.phases.length}, 任务数${totalTasks}`);

      res.json(success({
        ...result,
        stats: {
          beforeTaskCount,
          afterTaskCount: totalTasks,
          preservedCompletedTasks: completedTasks.length,
          cancelledTasks: deletedCount
        }
      }, '重新规划成功'));
    } catch (error) {
      logger.error('重新规划失败:', error.message);
      res.status(500).json(fail('重新规划失败'));
    }
  }

  static async checkReplan(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const allTasks = await LearningTaskModel.findByPlanId(planId, userId);
      const completedTasks = allTasks.filter(t => t.status === 2);
      const pendingTasks = allTasks.filter(t => t.status === 0);
      const inProgressTasks = allTasks.filter(t => t.status === 1);
      const skippedTasks = allTasks.filter(t => t.status === 3);

      const completionRate = allTasks.length > 0 
        ? completedTasks.length / allTasks.length 
        : 0;

      const overdueTasks = allTasks.filter(t => t.is_overdue === 1);
      const lowScoreTasks = completedTasks.filter(t => t.self_score !== null && t.self_score < 60);

      const maxPlannedDate = await LearningTaskModel.getMaxPlannedDate(planId, userId);
      const planEndDate = plan.end_date || plan.target_date;

      let needReplan = false;
      let reasons = [];

      if (completionRate < 0.3 && allTasks.length > 5) {
        needReplan = true;
        reasons.push('完成率过低');
      }

      if (overdueTasks.length > 3) {
        needReplan = true;
        reasons.push('存在多个超时任务');
      }

      if (lowScoreTasks.length >= 3) {
        needReplan = true;
        reasons.push('多次学习效果不佳');
      }

      if (maxPlannedDate && planEndDate && new Date(maxPlannedDate) > new Date(planEndDate)) {
        needReplan = true;
        reasons.push('预计完成日期已超过目标日期');
      }

      const ReplanLogModel = require('../models/ReplanLogModel');
      const lastReplan = await ReplanLogModel.getLatest(planId);

      res.json(success({
        needReplan,
        reasons,
        stats: {
          totalTasks: allTasks.length,
          completedTasks: completedTasks.length,
          pendingTasks: pendingTasks.length,
          inProgressTasks: inProgressTasks.length,
          skippedTasks: skippedTasks.length,
          overdueTasks: overdueTasks.length,
          lowScoreTasks: lowScoreTasks.length,
          completionRate: Math.round(completionRate * 100)
        },
        dates: {
          maxPlannedDate,
          planEndDate,
          isOverdue: maxPlannedDate && planEndDate && new Date(maxPlannedDate) > new Date(planEndDate)
        },
        lastReplan
      }));
    } catch (error) {
      logger.error('检查重规划需求失败:', error.message);
      res.status(500).json(fail('检查失败'));
    }
  }

  static async getReplanHistory(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const ReplanLogModel = require('../models/ReplanLogModel');
      const logs = await ReplanLogModel.findByPlanId(planId, { limit: 10 });

      res.json(success(logs));
    } catch (error) {
      logger.error('获取重规划历史失败:', error.message);
      res.status(500).json(fail('获取失败'));
    }
  }

  static async updatePlanSettings(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);
      const { dailyStudyMinutes, endDate } = req.body;

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const updateData = {};
      if (dailyStudyMinutes !== undefined) {
        updateData.dailyStudyMinutes = dailyStudyMinutes;
      }
      if (endDate !== undefined) {
        updateData.endDate = endDate;
      }

      if (Object.keys(updateData).length === 0) {
        return res.status(400).json(fail('没有需要更新的内容'));
      }

      await LearningPlanModel.update(planId, userId, updateData);

      logger.info(`更新计划设置: 计划${planId}, 数据${JSON.stringify(updateData)}`);

      res.json(success(null, '设置更新成功'));
    } catch (error) {
      logger.error('更新计划设置失败:', error.message);
      res.status(500).json(fail('更新失败'));
    }
  }

  static async updatePlanDeadline(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);
      const { endDate } = req.body;

      if (!endDate) {
        return res.status(400).json(fail('截止日期不能为空'));
      }

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const oldEndDate = plan.end_date || plan.target_date;

      await LearningPlanModel.update(planId, userId, { endDate });

      const timeDiff = new Date(endDate) - new Date(oldEndDate);
      const daysDiff = Math.ceil(timeDiff / (1000 * 60 * 60 * 24));

      logger.info(`更新计划截止日期: 计划${planId}, 旧日期${oldEndDate}, 新日期${endDate}, 差异${daysDiff}天`);

      res.json(success({
        oldEndDate,
        newEndDate: endDate,
        daysDiff
      }, '截止日期更新成功'));
    } catch (error) {
      logger.error('更新计划截止日期失败:', error.message);
      res.status(500).json(fail('更新失败'));
    }
  }

  static async addPlanTask(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);
      const { name, description, plannedDuration, plannedDate, phaseId, difficulty } = req.body;

      if (!name) {
        return res.status(400).json(fail('任务名称不能为空'));
      }

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const beforeStats = await LearningTaskModel.getTaskStatsByPlan(planId, userId);

      const taskId = await LearningTaskModel.createTask(userId, {
        planId,
        phaseId,
        name,
        description,
        plannedDuration: plannedDuration || 60,
        plannedDate,
        difficulty: difficulty || 2
      });

      const afterStats = await LearningTaskModel.getTaskStatsByPlan(planId, userId);

      const completionRateBefore = beforeStats.total > 0 
        ? Math.round((beforeStats.completed / beforeStats.total) * 100) 
        : 100;
      const completionRateAfter = afterStats.total > 0 
        ? Math.round((afterStats.completed / afterStats.total) * 100) 
        : 100;

      logger.info(`添加计划任务: 计划${planId}, 任务${taskId}, 名称${name}`);

      res.status(201).json(success({
        taskId,
        warning: {
          completionRateChanged: completionRateBefore !== completionRateAfter,
          completionRateBefore,
          completionRateAfter,
          message: completionRateAfter < completionRateBefore 
            ? `添加任务后，完成率将从 ${completionRateBefore}% 下降到 ${completionRateAfter}%` 
            : null
        }
      }, '任务添加成功'));
    } catch (error) {
      logger.error('添加计划任务失败:', error.message);
      res.status(500).json(fail('添加失败'));
    }
  }

  static async deletePlanTask(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);
      const taskId = parseInt(req.params.taskId);

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const task = await LearningTaskModel.findById(taskId, userId);
      if (!task) {
        return res.status(404).json(fail('任务不存在'));
      }

      if (task.plan_id !== planId) {
        return res.status(400).json(fail('任务不属于该计划'));
      }

      if (task.status === 2) {
        return res.status(400).json(fail('已完成的任务不能删除'));
      }

      const cancelled = await LearningTaskModel.cancel(taskId, userId);

      if (cancelled) {
        logger.info(`取消计划任务: 计划${planId}, 任务${taskId}`);
        res.json(success(null, '任务已取消'));
      } else {
        res.status(400).json(fail('取消失败'));
      }
    } catch (error) {
      logger.error('取消计划任务失败:', error.message);
      res.status(500).json(fail('取消失败'));
    }
  }

  static async updateStatus(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);
      const { status, reviewNotes } = req.body;

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      await LearningPlanModel.updateStatus(planId, userId, status);
      
      if (reviewNotes) {
        await LearningPlanModel.update(planId, userId, { reviewNotes });
      }

      cache.delete(`plan:${planId}:${userId}`);
      cache.deleteByPrefix('plans:' + userId);

      logger.info(`更新计划状态: 计划${planId}, 状态${status}`);

      res.json(success(null, '状态更新成功'));
    } catch (error) {
      logger.error('更新计划状态失败:', error.message);
      res.status(500).json(fail('更新失败'));
    }
  }

  static async getMotivation(req, res) {
    try {
      const userId = req.user.userId;
      const planId = parseInt(req.params.id);

      const plan = await LearningPlanModel.findById(planId, userId);
      if (!plan) {
        return res.status(404).json(fail('计划不存在'));
      }

      const MotivationAgent = require('../services/MotivationAgent');
      const motivation = await MotivationAgent.generate(plan);

      res.json(success(motivation));
    } catch (error) {
      logger.error('获取激励文案失败:', error.message);
      res.status(500).json(fail('获取失败'));
    }
  }

  static async checkCreateLimit(req, res) {
    try {
      const userId = req.user.userId;
      const result = await LearningPlanService.checkCreateLimit(userId);
      res.json(success(result));
    } catch (error) {
      logger.error('检查创建限制失败:', error.message);
      res.status(500).json(fail('检查失败'));
    }
  }
}

module.exports = PlanController;